### ISSUE TITLE
Automatic Updates for Test Runner

### ISSUE THREAD

**Issue by getsource** [WordPress/phpunit-test-runner#104]
Right now, any change in the test runner requires hosts to all update the runner manually.

This means that if/as breaking changes are found (see: #83) all hosts that are reporting fo tests need to update their setups to fix it.

Ideally, the test runner should require the least amount of feedback/maintenance work from hosts possible.

This could be resolved a few ways -- it might look like having the runner support updating itself, or that we update documentation so that it includes fetching/cloning the newest version of the runner.

**Comment by javiercasares** [comment]
I think this is done with the latest documentation. We suggest fetching the repo each time.
