### ISSUE TITLE
Add IONOS as Test Reporter

### ISSUE THREAD

**Issue by pfefferle** [WordPress/phpunit-test-runner#113]
Please add the IONOS bot for the test reportings.

Bot username: ionosbot
Email: wordpress-test-runner@ionos.com

**Comment by getsource** [comment]
Thanks so much!

I added the bot as a test reporter, and you should receive an invitation to the email address on the profile. Please let me know if you have any questions!

**Comment by pfefferle** [comment]
Hey @getsource thanks for adding, but I see an:

`An error occurred adding you to this site. Back to the homepage.` 

When clicking on the link

**Comment by getsource** [comment]
Oh, thanks for letting me know! That's odd.

I see it as added in the backend. Could you please see what happens if you try to log in using `ionosbot`
at https://make.wordpress.org/hosting/wp-admin ?

**Comment by pfefferle** [comment]
yes, sorry a colleague clicked the link ;)
