### ISSUE TITLE
Add `nexcessbot` as Test Reporter

### ISSUE THREAD

**Issue by boogah** [WordPress/phpunit-test-runner#117]
Bot username: `nexcessbot`
Bot email: `nx-runner@nexcess.net`

Thanks y'all!

**Comment by getsource** [comment]
Hi @boogah ! 👋🏻

Thanks so much for submitting this!

Since the results will be featured in the [hosting test results page](https://make.wordpress.org/hosting/test-results/), could you please update the WordPress.org profile  with a Logo/Gravatar and a URL?

**Comment by boogah** [comment]
@getsource Of course! URL and logo added!

**Comment by getsource** [comment]
Thanks much!

It's added, and you should receive an invitation to the email address on the profile. Please let me know if you have any questions!
