### ISSUE TITLE
Repository Wiki does not seem to work

### ISSUE THREAD

**Issue by jadonn** [WordPress/phpunit-test-runner#118]
The README says to use the repository wiki to record information about implementation details, but when I click on the link https://github.com/WordPress/phpunit-test-runner/wiki I am redirected to the main https://github.com/WordPress/phpunit-test-runner/.

**Comment by getsource** [comment]
I think the intention in the `README.md` is that individual organizations should use the wiki instead of `README.md` to record their details so that they can still use a fork/clone cleanly from here.

```The test suite runner is designed to be used without any file modification. Configuration happens with a series of environment variables (see .env.default for an annotated overview). Use the repository wiki to document implementation details, to avoid README conflicts with the upstream.```

It doesn't need to be like that, but maybe we can make it more clear?
