### ISSUE TITLE
Please Add "realznetlive" As test-reporter

### ISSUE THREAD

**Issue by Arvind-backupmx** [WordPress/phpunit-test-runner#125]
Dear Team,

We want to add and run this test, please proceed further.

Please Add "realznetlive" As test-reporter which is created on WordPress

**Comment by Arvind-backupmx** [comment]
Hello Team,

We will be happy to hear your revert on the same we are still not able to add/create an app password :)

**Comment by getsource** [comment]
Hi @Arvind-backupmx,

Thanks so much for submitting!

I took a look at the WordPress profile, and it doesn't currently make it very clear which host it is for.

Could you please update the profile (Name, Logo/Gravatar, URL) so that visitors to the hosting test results page (https://make.wordpress.org/hosting/test-results/) can tell who is contributing results?

Thanks much!

**Comment by Arvind-backupmx** [comment]
Thanks for the revert.

I did update the detail, sorry for the avatar there is no option for changing the avatar.

**Comment by Arvind-backupmx** [comment]
Good Afternoon, 

Once issue occurring at my end to performing the process, which is as below.'


I followed the require steps as below and at second last command [/opt/plesk/php/7.0/bin/php prepare.php] it was throwing the error as [Error: EACCES: permission denied, mkdir '/tmp/wp-runtest/node_modules/grunt-contrib-qunit/node_modules/puppeteer/.local-chromium' ] for more refere most below.
 
I understand the error as it says about permission but believe me there is no manual option to give permission as file prepair.php processing all the steps automatically.
 
Please check and let me know how can I fix it to report gain.
 
Steps I followed
-----------------------------------------------------------------------
1. create a webspace
2. create a database
3. clone git repo from https://github.com/WordPress/phpunit-test-runner.git
4. copy ".env.default" to ".env"
5. fill data in ".env" as appropriate to make sure scripts will be able to access the DB
6. append PATH=$PATH:/opt/plesk/node/12/bin
7. install node.js/grunt nmp install -g grunt-cli
8. run /opt/plesk/php/7.0/bin/php prepare.php   [ Issue is here]
9. run /opt/plesk/php/7.0/bin/php test.php
-----------------------------------------------------------------------

---------------------------------------------------------------------------------
  path: '/tmp/wp-runtest/node_modules/node-sass/vendor'
}

> puppeteer@1.20.0 install /tmp/wp-runtest/node_modules/grunt-contrib-qunit/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: EACCES: permission denied, mkdir '/tmp/wp-runtest/node_modules/grunt-contrib-qunit/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/tmp/wp-runtest/node_modules/grunt-contrib-qunit/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/tmp/wp-runtest/node_modules/grunt-contrib-qunit/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/tmp/wp-runtest/node_modules/grunt-contrib-qunit/node_modules/puppeteer/.local-chromium'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-08T07_03_14_832Z-debug.log
Error: Failed to perform operation.
---------------------------------------------------------------------------------

**Comment by getsource** [comment]
You can change the avatar by setting a [Gravatar](https://gravatar.com) with the email address used for the WordPress profile.

On the latter, it looks like the issue is here:
```
ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: EACCES: permission denied, mkdir '/tmp/wp-runtest/node_modules/grunt-contrib-qunit/node_modules/puppeteer/.local-chromium'
```

I'd recommend checking into whether the permissions set allow the build script (and whatever user it is being run with) to create that directory. Less likely, but possible -- I'd double-check if there is enough space in `/tmp` for Chromium to download.

I'm not 100% sure whether Chromium is necessary for the build to complete. It might only limit some of the JS tests, which aren't currently run with the test-runner. You could test and see if setting the environment variable noted allows it to proceed.

**Comment by Arvind-backupmx** [comment]
Thanks for the revert, 

I have updated the avatar now,

Further about the error, I'm still getting the same, even having much space on the /tmp volume, I also not able to see any other way to run the repair PHP by excluding such error or dependency

please let me know how can i use this script on our server without any error, as per the given requisite, on the git ReadMe file, all of are availbe at my end.

**Comment by pfefferle** [comment]
Is PHP allowed to write to the `/tmp` file? Otherwise can try to use a different folder as temp? The `env` var for that is `WPT_PREPARE_DIR`.

**Comment by Arvind-backupmx** [comment]
thanks a lot for reply 

I'm running the all code as root

my git report is at : /root/wp-test/new/
i have created the folder : WPT_PREPARE_DIR is /root/wp-test/new/new-test

**Comment by Arvind-backupmx** [comment]
at Object.<anonymous> (/tmp/new-test/node_modules/grunt-contrib-qunit/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/tmp/new-test/node_modules/grunt-contrib-qunit/node_modules/puppeteer/.local-chromium'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-08T10_35_07_733Z-debug.log
Error: Failed to perform operation.

**Comment by Arvind-backupmx** [comment]
Hello

As per the error

Error: EACCES: permission denied, mkdir '/tmp/new-test/node_modules/grunt-contrib-qunit/node_modules/puppeteer/.local-chromium'


Im not even able to create the folder manualy, see the result

[root@wpmanaged new]# mkdir '/tmp/new-test/node_modules/grunt-contrib-qunit/node_modules/puppeteer/.local-chromium'
mkdir: cannot create directory ‘/tmp/new-test/node_modules/grunt-contrib-qunit/node_modules/puppeteer/.local-chromium’: No such file or directory


and when appending "-p" work

mkdir -p '/tmp/new-test/node_modules/grunt-contrib-qunit/node_modules/puppeteer/.local-chromium'


Which seems issue in the project, that need to be check, becase same thing not working at another server as well. and getting same error.

**Comment by Arvind-backupmx** [comment]
Now please suggest on this,


I will wait for next update from anyone who can resolve this.
