### ISSUE TITLE
SHIFTER Test Reporter

### ISSUE THREAD

**Issue by sawanoboly** [WordPress/phpunit-test-runner#126]
Hi.

We'd like to complete our test reporter setup. The info we've registered for this at WP.org is the following:

Username | Email
-- | --
shifterbot | shifterbot@getshifter.io

Thanks,

**Comment by getsource** [comment]
Added; thanks much!

You should get a confirmation email soon, after which you should be able to generate/view your API key from within your profile in the https://make.wordpress.org/hosting/wp-admin panel.

Please let me know if you run into any trouble!

**Comment by sawanoboly** [comment]
@getsource 

We issued an API key and set the environment variable as follows,


```
export WPT_REPORT_API_KEY='shifterbot:xxxx xxxx xxxx xxxx xxxx xxxx'
```


However, the report command fails. Is there some element missing?

```
$ php report.php

...

Error: Error uploading results: The provided password is an invalid application password. (HTTP status 401)
```

**Comment by getsource** [comment]
That looks correct!

I'm assuming you have run `source .env` in your script, or command line before you run `report.php` alone, in the example you gave.

I took a look in the admin panel, and I'm noticing that for me, there are two fields for adding application passwords:
<img width="1067" alt="Screen Shot 2020-10-20 at 17 41 25" src="https://user-images.githubusercontent.com/1034160/96562251-8442e580-12fb-11eb-8b9e-f92b3fb78a8c.png">

I'm so sorry about that!
I'm wondering if something broke when application passwords were added to core, as they were being used on `make.wordpress.org` before that.

Assuming you are seeing the same thing, could you try creating an application password with the other "Add New" field to see if maybe it works better?

**Comment by sawanoboly** [comment]
![Profile ‹ Make WordPress Hosting — WordPress 2020-10-20 18-56-52](https://user-images.githubusercontent.com/272388/96571053-0932fc80-1306-11eb-96a2-44e66c3b82b7.png)


@getsource Thank you for your comment 😃 

There are two on my dashboard as well, and only the button at the top works. And it registers to both. I've done it a few times and it works like that...

**Comment by sawanoboly** [comment]
https://make.wordpress.org/hosting/test-results/r49309/shifterbot-r49309/

The plugin table was back to one, so I issued a new Application Password and the report was sent successfully. Thank you!

**Comment by getsource** [comment]
That's so great, thank you!
Sorry, I forgot to comment here that the application password plugin was deactivated (to make it just one table).

I'm glad to hear it fixed things!
