### ISSUE TITLE
Feedback: please consider to remove GLOB_BRACE from unittest functions.

### ISSUE THREAD

**Issue by sawanoboly** [WordPress/phpunit-test-runner#128]
One of the unit tests uses the GLOB_BRACE option for glob.

https://github.com/digitalcube/wordpress-develop/blob/master/tests/phpunit/tests/image/functions.php#L22-L27

The GLOB_BRACE option is not supported by some libc-compatible implementations. Solaris is shown as an example in the documentation, but it cannot use this option on other implementations, such as alpine linux, which uses musl-libc.

https://www.php.net/manual/en/function.glob.php

I'd like to see them switch to an implementation that doesn't use GLOB_BRACE, as it seems to be just cleaning up the files, regardless of compatibility.

**Comment by kittenkamala** [comment]
https://core.trac.wordpress.org/ticket/51661

**Comment by getsource** [comment]
This was fixed in https://core.trac.wordpress.org/changeset/49450

Thanks so much @sawanoboly and @kittenkamala !
