### ISSUE TITLE
Test Reporter request

### ISSUE THREAD

**Issue by ramonfincken** [WordPress/phpunit-test-runner#129]
We'd like to complete our test reporter setup. The info we've registered for this at WP.org is the following:

Username | Email
-- | --
managedwphostingbot | managedwphostingwpmakebot at managedwphosting dot nl

php prepare.php and php test.php are fine

**Comment by getsource** [comment]
Added; thanks much!

You should get a confirmation email soon, after which you should be able to generate/view your API key from within your profile in the https://make.wordpress.org/hosting/wp-admin panel.

Please let me know if you run into any trouble!

**Comment by ramonfincken** [comment]
Will start on submitting tomorrow !

**Comment by ramonfincken** [comment]
Could not resist doing it today
https://make.wordpress.org/hosting/test-results/r49487/managedwphostingbot-r49487/

**Comment by pfefferle** [comment]
this was really fast!
