### ISSUE TITLE
Collect Additional Image Manipulation Environment Data

### ISSUE THREAD

**Issue by getsource** [WordPress/phpunit-test-runner#131]
As part of this discussion, on what hosts would support `webp` if it were enabled in core:
https://wordpress.slack.com/archives/C02RQBWTW/p1605269402382600

I think it'd be good if we started to collect some environment data on types of images supported, and maybe tools / libraries available on the system, to help inform media features.

Any thoughts on that, and if agreed it's a good idea, what details would be best to collect?

**Comment by sven-wordpress** [comment]
Add: https://core.trac.wordpress.org/ticket/35725#comment:27

**Comment by sven-wordpress** [comment]
Happy to support it on my hosting.

First things to collect are:

- Webserver (Apache etc.)
- PHP Version
- GD implemented
- Imagick implemented

**Comment by sven-wordpress** [comment]
Sorry, I'm out. Don't want to waste my time. Comment # 52 here is respectless.
https://core.trac.wordpress.org/ticket/35725

**Comment by getsource** [comment]
Just a quick note that I still think it'd be great to collect this information so that we know what formats are supported at the system level, whether this happens primarily in the test runner, or elsewhere.

**Comment by adamsilverstein** [comment]
@getsource This does feel like valuable information to collect to make more informed decisions in core about image formats. I'm not that familiar with how this project works (and haven't tested), hopefully this will add the info we need: https://github.com/WordPress/phpunit-test-runner/pull/134

**Comment by adamsilverstein** [comment]
Fixed in https://github.com/WordPress/phpunit-test-runner/pull/134, This issue can be closed.
