### ISSUE TITLE
Coding Standards

### ISSUE THREAD

**Issue by mrxkon** [WordPress/phpunit-test-runner#139]
I do understand that technically the files here aren't part of WP itself and I know that the typical way is to not focus on CS rewrites on existing code usually.

It is part of the ecosystem though and the codebase here isn't that big so the changes should be pretty straightforward and easy to follow.

Would it be possible to show some WPCS ❤️ ?

(I'd be more than happy to provide a PR for this also btw.)

**Comment by javiercasares** [comment]
We tried, but it's not easy because, for example, it WPCS tells about using wp_json functions that don't exist because this is not a WordPress.

For the latest releases, we tried to improve the documentation and best practices. Right now is the best we can do, but we will check and fix the most.
