### ISSUE TITLE
Test Reporter for cynderhostbot

### ISSUE THREAD

**Issue by jk2625** [WordPress/phpunit-test-runner#141]
Hi everyone,

Can a Test Reporter be added for:

Username: cynderhostbot (https://profiles.wordpress.org/cynderhostbot/)
Email: support@cynderhost.com

Thanks!

~ John

**Comment by pfefferle** [comment]
Added; thanks much!

You should get a confirmation email soon, after which you should be able to generate/view your API key from within your profile in the https://make.wordpress.org/hosting/wp-admin panel.

Please let me know if you run into any trouble!
