### ISSUE TITLE
New Web Testing bot request

### ISSUE THREAD

**Issue by redscott** [WordPress/phpunit-test-runner#142]
Hello Guys,
Can you please add 'redithostingbot2' into the PHPUnit testing group for me please.
I plan on continue to run tests as currently done on PHP7.4 but will use the new bot for PHP8.x
I've set the bot up as far as I can but I can't do much more at the moment as its not linked to the make.wordpress.org group.

Thanks,
Scott

**Comment by pfefferle** [comment]
Added; thanks much!

You should get a confirmation email soon, after which you should be able to generate/view your API key from within your profile in the https://make.wordpress.org/hosting/wp-admin panel.

Please let me know if you run into any trouble!

**Comment by redscott** [comment]
Hello,
Looks like its not right.

> You attempted to access the "Make WordPress Hosting" dashboard, but you do not currently have privileges on this site. If you believe you should be able to access the "Make WordPress Hosting" dashboard, please contact your network administrator.

**Comment by redscott** [comment]
OK I take it back, third different browser worked.
