### ISSUE TITLE
Test Reporter: NameHeroBot

### ISSUE THREAD

**Issue by mmuyskens** [WordPress/phpunit-test-runner#145]
Please add @nameherobot as Test Reporter.

Email: webhosting916@gmail.com (yes, it's a monitored email)

Cheers!

Mark

**Comment by getsource** [comment]
Hi!
Sorry for the long wait on a reply, and thank you for setting up the test runner!

Would you mind setting the email address to one that uses the domain name of the host?

That way, it can help verify the account is from the host, and if anyone ever moves between companies (or the job responsibilities change), the address is still reachable by someone at the host.

Thanks so much!

**Comment by pfefferle** [comment]
@mmuyskens friendly ping :)
