### ISSUE TITLE
Test reporter bot registration

### ISSUE THREAD

**Issue by raimundas** [WordPress/phpunit-test-runner#146]
Howdy,

How do I exactly register the "Bot account" for test reporting? 
I have recently set up "phpunit-test-runner" and the test.php finally passes tests.
I have registered an account on WordPress.org, but can't find a "bot registration" link.

I want to register a bot with name "HostensBot" and email "info@hostens.com".

Many thanks in advance.

**Comment by javiercasares** [comment]
Hello @raimundas 

You can check https://make.wordpress.org/hosting/handbook/handbook/tests/#how-to-report-creating-your-bot-for-wordpress-org

**Comment by raimundas** [comment]
Hello,

Thanks for the info! Looks like I was almost there.
I'll open a clean request.
