### ISSUE TITLE
Test Reporter: Name Hostens

### ISSUE THREAD

**Issue by raimundas** [WordPress/phpunit-test-runner#147]
Hello,

Please include "hostens" as a Test Reporter.

Username/Botname: hostens
email: info@hostens.com

Website: https://www.hostens.com/

Thanks.

**Comment by pfefferle** [comment]
Hello @raimundas can you please add a link to your website, to the bot profile?

**Comment by raimundas** [comment]
Hello @pfefferle Ihave added a link to our website in the first comment.

**Comment by pfefferle** [comment]
Sorry, if my answer was a bit confusing, I meant to add the URL to the WordPress profile, you added: https://profiles.wordpress.org/hostens/

Because we use that link, to link to your page from the test results page: https://make.wordpress.org/hosting/test-results/

**Comment by raimundas** [comment]
Hello, 

We have added the URL to the WordOress profile now.
Thanks for clarifying.

**Comment by pfefferle** [comment]
Added; thanks much!

You should get a confirmation email soon, after which you should be able to generate/view your API key from within your profile in the https://make.wordpress.org/hosting/wp-admin panel.

Please let me know if you run into any trouble!
