### ISSUE TITLE
Test Reporter: forgetwpbot

### ISSUE THREAD

**Issue by forgetwp** [WordPress/phpunit-test-runner#148]
Hiya, 
Could you please add @forgetwpbot as a Test Reporter

Email support@forgetwp.com
https://forgetwp.com

With Thanks,

**Comment by pfefferle** [comment]
Added; thanks much!

You should get a confirmation email soon, after which you should be able to generate/view your API key from within your profile in the https://make.wordpress.org/hosting/wp-admin panel.

Please let me know if you run into any trouble!
