### ISSUE TITLE
Error: The PHPUnit Polyfills library is a requirement for running the WP test suite.

### ISSUE THREAD

**Issue by rafalkukla** [WordPress/phpunit-test-runner#154]
Hi all, 

For the past few weeks after running `php prepare.php` and then `php test.php` I have an error message "**Error: The PHPUnit Polyfills library is a requirement for running the WP test suite.**"

In order to fix it, I have to go back to the wordpress folder, and run `composer update` then go back to phpunit-test-runner so I can carry on testing.

**Comment by javiercasares** [comment]
this should be fixed in the latest release.
