### ISSUE TITLE
request to add test bot to wordpress.org

### ISSUE THREAD

**Issue by lara-fernandezcueto** [WordPress/phpunit-test-runner#157]
Could the user stratobot be added as "Test Reporter" as indicated in https://make.wordpress.org/hosting/test-results-getting-started/?

**Comment by pfefferle** [comment]
Hey @lara-fernandezcueto

thanks for setting up the test bot!

Could you please update the WordPress profile of the bot to add the URL of Strato and an Icon (Gravatar), since that's used on the test results page (https://make.wordpress.org/hosting/test-results/)?

**Comment by lara-fernandezcueto** [comment]
Hi @pfefferle 

the bot has been updated with the URL and the Avatar has been uploaded to Gravatar

thanks for pointing that out

**Comment by pfefferle** [comment]
Added; thanks much!

You should get a confirmation email soon, after which you should be able to generate/view your API key from within your profile in the https://make.wordpress.org/hosting/wp-admin panel.

Please let me know if you run into any trouble!
