### ISSUE TITLE
Add new test reporter

### ISSUE THREAD

**Issue by timiwahalahti** [WordPress/phpunit-test-runner#162]
Hello team! Can you please add user "[digitoimistodude](https://profiles.wordpress.org/digitoimistodude/)" as a new test reporter? Thanks!

**Comment by pfefferle** [comment]
Added; thanks much!

You should get a confirmation email soon, after which you should be able to generate/view your API key from within your profile in the https://make.wordpress.org/hosting/wp-admin panel.

Please let me know if you run into any trouble!
