### ISSUE TITLE
Please create bot user for wp test reporting

### ISSUE THREAD

**Issue by RamunasCereskevicius** [WordPress/phpunit-test-runner#163]
Hi,

I am representing hostinger.com . We would like to run tests in our environment on various php versions. We have everything set up already on our side, just need report_api_key.

wordpress account username: hostinger
wordpress account associated email: admins@hostinger.com

Please let me know if anything else is needed

**Comment by pfefferle** [comment]
hey @RamunasCereskevicius 

Thanks for the request! Can you please upload an avatar and add the URL to the hoster to your profile? The profile will be used on the test results page: https://make.wordpress.org/hosting/test-results/

**Comment by RamunasCereskevicius** [comment]
Hi again,

Logo uploaded. URL is already set to https://www.hostinger.com/wordpress-hosting

**Comment by pfefferle** [comment]
Added; thanks much!

You should get a confirmation email soon, after which you should be able to generate/view your API key from within your profile in the https://make.wordpress.org/hosting/wp-admin panel.

Please let me know if you run into any trouble!

**Comment by RamunasCereskevicius** [comment]
Hi,

We have integrated the tests, but it seems there is no link attached to our logo here: https://make.wordpress.org/hosting/test-results/ even though we have a link set in the profile?
![image](https://user-images.githubusercontent.com/50201931/146893525-05376da9-9962-458e-96dc-b2aca6e283d4.png)

Are we missing anything?
