### ISSUE TITLE
Add the `--dont-report-useless-tests` flag by default.

### ISSUE THREAD

**Issue by costdev** [WordPress/phpunit-test-runner#167]
**Is your feature request related to a problem? Please describe.**
The [Hosting Test Results](https://make.wordpress.org/hosting/test-results/) page shows a significant number of "Failed" test runs. This is due to risky tests that were exposed after a recent commit in WordPress Core. In this case, the tests in question do not perform any assertions.

**Describe the solution you'd like**
By adding the `--dont-report-useless-tests` flag by default, this allows the test runner to report true failures in the tests.

If the reporting of useless tests is desired, a `WPT_PHPUNIT_CMD` value can be added to the `.env` file that doesn't include this flag.

**Describe alternatives you've considered**
- Each host adds a `WPT_PHPUNIT_CMD` value to their `.env` file which adds the `--dont-report-useless-tests` flag. However, as this situation will cause failures across the board, all hosts would need to add this. At that point, I concluded that it might as well be a default.
- Adding the `beStrictAboutTestsThatDoNotTestAnything="false"` attribute to the PHPUnit configuration file. - There is no PHPUnit configuration file in the repository. Opted for the `--dont-report-useless-tests` flag instead.
- Fixing the risky tests. This has already been started by core developers and the work is ongoing. Until these are resolved, the Hosting Test Results will continue to show "Failed" for all hosts that aren't running with the `--dont-report-useless-tests` flag. If any future commits reveal more risky tests, history will repeat itself.
- Add the `@doesNotPerformAssertions` annotation to the tests. - This means that the tests won't be reported at all, even to Core developers. This might also be mislabeled and, in fact, merely be a test that hasn't been implemented yet. This is a common occurrence with abstract parent class method that requires the test method to exist whether it performs assertions or not.

**Additional context**
I posted in the hosting-community Slack channel requesting a test to be done on a Host system. @riper81 kindly ran some tests and by adding the `--dont-report-useless-tests` flag to the command in `test.php`, the [Kinsta test run](https://make.wordpress.org/hosting/test-results/r52449/kinstabot-r52449/) passed.

**Comment by pfefferle** [comment]
The IONOS test run also passes with the `--dont-report-useless-tests` flag: https://make.wordpress.org/hosting/test-results/r52449/ionosbot-r52449/

**Comment by riper81** [comment]
Indeed - I confirm that all tests started passing after @costdev suggested to add that flag on the test.php file. Once that was added all the tests from us (Kinsta.com) started passing again. I can see besides IONOS, the folks from SiteGround applied the flag and their tests started passing as well. So it would be a good idea to include on the official documentation.
