### ISSUE TITLE
Include a bot [wpsaedgebot]

### ISSUE THREAD

**Issue by javiercasares** [WordPress/phpunit-test-runner#172]
Profile: https://profiles.wordpress.org/wpsaedgebot/
Username: wpsaedgebot
Email: wpsaedgebot@wpsysadmin.com

I'll have the bot [wpsabot] for the actual configuration (right now, PHP 7.4 + MariaDB 10.5) and then, the [wpsaedgebot] will be configured to report the latest server configuration (probably will give failed tests).

**Comment by getsource** [comment]
Looks good -- thanks so much!

I added the test reporter account, and you should receive an invitation to the email address on the `wpsaedgebot` WordPress.org profile.

Please let me know if you have any questions!
