### ISSUE TITLE
Include a new bot: cloudingbot

### ISSUE THREAD

**Issue by javiercasares** [WordPress/phpunit-test-runner#173]
Profile: https://profiles.wordpress.org/cloudingbot/
Username: cloudingbot
Email: patricia.armesto@clouding.io

**Comment by getsource** [comment]
Looks good -- thanks so much!

I added the test reporter account, and you should receive an invitation to the email address on the `cloudingbot` WordPress.org profile.

Please let me know if you have any questions!
