### ISSUE TITLE
Second ICDSoft Test Reporter

### ISSUE THREAD

**Issue by korikori** [WordPress/phpunit-test-runner#185]
Hello,

Our company, ICDSoft, would like to send out test reports with a second user (for MySQL 8). Our second WordPress.org user:

icdsoftbot2
[abuse@icdsoft.com](mailto:abuse@icdsoft.com)

Thank you in advance,
Stanimir

**Comment by korikori** [comment]
Yes, the mailbox is monitored by members of the same team on our end that will be working with the test runner, so this shouldn't be an issue.

**Comment by pfefferle** [comment]
OK, added; thanks much!

You should get a confirmation email soon, after which you should be able to generate/view your API key from within your profile in the https://make.wordpress.org/hosting/wp-admin panel.

Please let me know if you run into any trouble!
