### ISSUE TITLE
[Test Reporter] webnorth.dk

### ISSUE THREAD

**Issue by ilmarsmillers** [WordPress/phpunit-test-runner#192]
Requesting your bot user to be added to this WordPress.org site as a “Test Reporter” (https://make.wordpress.org/hosting/test-results/).

For more information, please visit the [Getting Started](https://make.wordpress.org/hosting/test-results-getting-started/) Guide or the [Hosting Handbook](https://make.wordpress.org/hosting/handbook/tests/).

**Preconditions Checklist:**

* [x] I've added a Gravatar/logo to the profile.
* [x] I've added a URL to the profile, to make it clear to users what hosting company is being represented in the results.
* [x] I've set the email address to something monitored by a human.
* [x] I've set the email address to one that uses the domain name of the hosting company.

**Bot Profile Details:**

* Bot email address: dev@webrnoth.dk
* Bot WordPress profile: https://profiles.wordpress.org/webnorthdk

**Comment by pfefferle** [comment]
Hey @ilmarsmillers thanks for your request, but we need to know the wp.org profile you want to be added.

**Comment by ilmarsmillers** [comment]
> Hey @ilmarsmillers thanks for your request, but we need to know the wp.org profile you want to be added. (See "Bot Profile Details")

Hey @pfefferle, I updated initial post with visible e-mail and profile.

**Comment by Crixu** [comment]
I added the user webnorthdk as a "Test Reporter"

**Comment by Crixu** [comment]
@ilmarsmillers you should have received an invite on the email to join the network site.

**Comment by ilmarsmillers** [comment]
@Crixu thanks, got it, will run next week.
