### ISSUE TITLE
Add seravotestbot as "Test Reporter"

### ISSUE THREAD

**Issue by pekkakortelainen** [WordPress/phpunit-test-runner#197]
Hi!

Please add `seravotestbot` as a new test reporter.

wordpress.org: https://profiles.wordpress.org/seravotestbot/
email: hostmaster@seravo.com

**Comment by Crixu** [comment]
You got added to make.wordpress.org/hosting

Please make sure to follow the checklist:


- [ ]  I've added a Gravatar/logo to the profile.
- [ ]  I've added a URL to the profile, to make it clear to users what hosting company is being represented in the results.
- [ ]  I've set the email address to something monitored by a human.
- [ ]  I've set the email address to one that uses the domain name of the hosting company.

**Comment by pekkakortelainen** [comment]
Thank you @Crixu for the help, all set with the checklist items.
