### ISSUE TITLE
[Test Reporter] wnpowerbot

### ISSUE THREAD

**Issue by fedealvz** [WordPress/phpunit-test-runner#203]
Requesting `wnpowerbot` user to be added to this WordPress.org site [as a “Test Reporter”](https://make.wordpress.org/hosting/test-results/).

**Preconditions Checklist:**

* [x] I've added a Gravatar/logo to the profile.
* [x] I've added a URL to the profile, to make it clear to users what hosting company is being represented in the results.
* [x] I've set the email address to something monitored by a human.
* [x] I've set the email address to one that uses the domain name of the hosting company.

**Bot Profile Details:**

* Bot email address: wordpress@wnpower.com
* Bot WordPress profile: https://profiles.wordpress.org/wnpowerbot/

**Comment by javiercasares** [comment]
You should get a confirmation email soon, after which you should be able to generate/view your API key from within your profile in the https://make.wordpress.org/hosting/wp-admin/ panel.

**Comment by fedealvz** [comment]
Muchas gracias Javier :)
