### ISSUE TITLE
Help needed : Test stopped working due to npm error

### ISSUE THREAD

**Issue by ramonfincken** [WordPress/phpunit-test-runner#210]
First of all: I am not friends with npm,npm/node, it is a black box to me.
I need some guidance to get the runner working again.

So ... this happens now:

cd '/home/myuser/prepare'; npm install && npm run build

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: [WordPress@6.5.0](mailto:WordPress@6.5.0)
npm ERR! Found: [prettier@2.6.2](mailto:prettier@2.6.2)
npm ERR! node_modules/prettier
npm ERR!   dev prettier@["npm:wp-prettier@2.6.2"](mailto:npm:wp-prettier@2.6.2) from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer prettier@">=3" from @wordpress/prettier-config@3.8.1
npm ERR! node_modules/@wordpress/prettier-config
npm ERR!   dev @wordpress/prettier-config@"3.8.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/runnervm194h/npm-cache/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runnervm194h/npm-cache/_logs/2024-03-05T15_08_12_802Z-debug-0.log
Error: Failed to perform operation.

**Comment by ramonfincken** [comment]
remove Bug label
add Help wanted label

**Comment by javiercasares** [comment]
Hello, @ramonfincken.

This probably means that you have an outdated version of some software needed.

The first thing is checking the Node.js version. It should be at least 16.x (recommended 18.x) for the actual WordPress version.

If it's not, upgrade it to one of those versions, and it should work just fine.

If it doesn't work, please, ping again and I'll help you with the next steps :)

**Comment by ramonfincken** [comment]
We are on cloudlinux cpanel.

Even when entering /prepare with
source /home/myuser/nodevenv/prepare/18/bin/activate

[prepare (18)] [myuser@vm prepare]$ node -v
v18.18.2

it breaks

[prepare (18)] [myuser@vm prepare]$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: WordPress@6.6.0
npm ERR! Found: prettier@2.6.2
npm ERR! node_modules/prettier
npm ERR!   dev prettier@"npm:wp-prettier@2.6.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer prettier@">=3" from @wordpress/prettier-config@3.8.1
npm ERR! node_modules/@wordpress/prettier-config
npm ERR!   dev @wordpress/prettier-config@"3.8.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/myuser/npm-cache/_logs/2024-04-02T18_54_34_124Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /home/myuser/npm-cache/_logs/2024-04-02T18_54_34_124Z-debug-0.log


LOG ->



eresolve log:
https://pastebin.com/DJDT0Q09

# npm resolution error report

While resolving: WordPress@6.6.0
Found: prettier@2.6.2
node_modules/prettier
  dev prettier@"npm:wp-prettier@2.6.2" from the root project

Could not resolve dependency:
peer prettier@">=3" from @wordpress/prettier-config@3.8.1
node_modules/@wordpress/prettier-config
  dev @wordpress/prettier-config@"3.8.1" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

**Comment by ramonfincken** [comment]
can't we download some prepared archive ?

as we only run PHP unit tests, we do not run any javascript right ?

**Comment by ramonfincken** [comment]
Installed it a another server and now it runs.
