### ISSUE TITLE
[Test Reporter] add evermadebot

### ISSUE THREAD

**Issue by timiwahalahti** [WordPress/phpunit-test-runner#211]
**Preconditions Checklist:**

* [x] I've added a Gravatar/logo to the profile.
* [x] I've added a URL to the profile, to make it clear to users what hosting company is being represented in the results.
* [x] I've set the email address to something monitored by a human.
* [x] I've set the email address to one that uses the domain name of the hosting company.

**Bot Profile Details:**

* Bot email address: [redacted]
* Bot WordPress profile: https://profiles.wordpress.org/evermadebot/

**Comment by Crixu** [comment]
I sent you an invite @timiwahalahti to the mentioned email. 
You can now go ahead and request the API keys and finish the last step according to the instructions:
https://make.wordpress.org/hosting/handbook/tests/#how-to-report-creating-your-bot-for-wordpress-org
