### ISSUE TITLE
[Test Reporter] add veerotechbot

### ISSUE THREAD

**Issue by arunveero** [WordPress/phpunit-test-runner#215]
Requesting veerotechbot to be added to this WordPress.org site [as a “Test Reporter”](https://make.wordpress.org/hosting/test-results/).

**Preconditions Checklist:**

* [x] I've added a Gravatar/logo to the profile.
* [x] I've added a URL to the profile, to make it clear to users what hosting company is being represented in the results.
* [x] I've set the email address to something monitored by a human.
* [x] I've set the email address to one that uses the domain name of the hosting company.

**Bot Profile Details:**

* Bot email address: wpcom@veerotech.net 
* Bot WordPress profile: [https://profiles.wordpress.org/veerotechbot](https://profiles.wordpress.org/veerotechbot/)

**Comment by Crixu** [comment]
Thank you for the issue. I created your user and you should be able to retrieve your API Key from make.wordpress.org/hosting/wp-admin
