### ISSUE TITLE
Domaintechnik Test Reporter

### ISSUE THREAD

**Issue by at-benni** [WordPress/phpunit-test-runner#216]
Requesting your bot user to be added to this WordPress.org site [as a “Test Reporter”](https://make.wordpress.org/hosting/test-results/).

**Preconditions Checklist:**

* [x] I've added a Gravatar/logo to the profile.
* [x] I've added a URL to the profile, to make it clear to users what hosting company is being represented in the results.
* [x] I've set the email address to something monitored by a human.
* [x] I've set the email address to one that uses the domain name of the hosting company.

**Bot Profile Details:**

* Bot email address: wordpress@domaintechnik.at
* Bot WordPress profile: https://profiles.wordpress.org/domaintechnikbot/

**Comment by Crixu** [comment]
Thank you for the issue. I created your user and you should be able to retrieve your API Key from make.wordpress.org/hosting/wp-admin

**Comment by at-benni** [comment]
Thanks @Crixu for the quick reaction, the wp-admin page of make.wordpress.org/hosting/ redirects me to the bot WordPress profile page at profiles.wordpress.org and I cannot create the api key

**Comment by Crixu** [comment]
Have you accepted the email confirmation you should have received on the mentioned email?

**Comment by at-benni** [comment]
Sorry I overlooked that mail, thank you very much!
