### ISSUE TITLE
[Test Reporter] cloupsyhostingbot

### ISSUE THREAD

**Issue by kapc0403** [WordPress/phpunit-test-runner#224]
**Preconditions Checklist:**

- [x]  I've added a Gravatar/logo to the profile.
- [x]  I've added a URL to the profile, to make it clear to users what hosting company is being represented in the results.
- [x]  I've set the email address to something monitored by a human.
- [x]  I've set the email address to one that uses the domain name of the hosting company.

**Bot Profile Details:**

- Bot email address: kp@cloupsy.com
- Bot WordPress profile: https://profiles.wordpress.org/cloupsyhostingbot/

**Comment by kapc0403** [comment]
Thanks @pfefferle, I have corrected the email.

**Comment by pfefferle** [comment]
Thanks so much!

I added the bot as a test reporter, and you should receive an invitation to the email address on the profile. Please let me know if you have any questions!
