### ISSUE TITLE
[Test Reporter] CloudPress

### ISSUE THREAD

**Issue by kwatson** [WordPress/phpunit-test-runner#226]
Requesting your bot user to be added to this WordPress.org site [as a “Test Reporter”](https://make.wordpress.org/hosting/test-results/).

For more information, please visit the [Getting Started](https://make.wordpress.org/hosting/test-results-getting-started/) Guide or the [Hosting Handbook](https://make.wordpress.org/hosting/handbook/tests/).

**Preconditions Checklist:**

* [X] I've added a Gravatar/logo to the profile.
* [X] I've added a URL to the profile, to make it clear to users what hosting company is being represented in the results.
* [X] I've set the email address to something monitored by a human.
* [X] I've set the email address to one that uses the domain name of the hosting company.

**Bot Profile Details:**

* Bot email address: wphostbot@cloudpress.com
* Bot WordPress profile: https://profiles.wordpress.org/cloudpressbot

**Comment by pfefferle** [comment]
Thanks so much!

I added the bot as a test reporter, and you should receive an invitation to the email address on the profile. Please let me know if you have any questions!
