### ISSUE TITLE
[Test Reporter] Rocket.Net

### ISSUE THREAD

**Issue by zunaid321** [WordPress/phpunit-test-runner#227]
Requesting your bot user to be added to this WordPress.org site [as a “Test Reporter”](https://make.wordpress.org/hosting/test-results/).

For more information, please visit the [Getting Started](https://make.wordpress.org/hosting/test-results-getting-started/) Guide or the [Hosting Handbook](https://make.wordpress.org/hosting/handbook/tests/).

**Preconditions Checklist:**

* [x] I've added a Gravatar/logo to the profile.
* [x] I've added a URL to the profile, to make it clear to users what hosting company is being represented in the results.
* [x] I've set the email address to something monitored by a human.
* [x] I've set the email address to one that uses the domain name of the hosting company.

**Bot Profile Details:**

* Bot email address: hello@rocket.net
* Bot WordPress profile: https://profiles.wordpress.org/rocketdotnetbot/

**Comment by Crixu** [comment]
Hi @zunaid321  I added the user as a Test Reporter. You should now be able to login at make.wordpress.org/hosting/wp-admin to get your keys.

**Comment by pfefferle** [comment]
@zunaid321 btw. your email looks like a public email (maybe for support), be sure that your devs are able to access it, because the test-reporter sends the issues to this email address.

**Comment by chaion07** [comment]
Just checking in as I initially wanted to help @zunaid321 with the Test Reporter set up. Is there anything else we need to do from our end from the Hosting Team's perspective as I can see that the Rocket.Net WordPress Profile has been disabled a few minutes ago. Thanks!

**Comment by pfefferle** [comment]
what do you mean by "disabled"?

Maybe it is because of: https://make.wordpress.org/plugins/2024/06/29/password-reset-required-for-plugin-authors/

**Comment by zunaid321** [comment]
This is the current situation now:

![image](https://github.com/WordPress/phpunit-test-runner/assets/5287486/b8707ec1-1d19-4cb9-b423-cf2dd6c15d33)

**Comment by pfefferle** [comment]
Can you try the password reminder?

**Comment by pfefferle** [comment]
I am not aware that we done something, so maybe try to send an email to the forum-password-reset email mentioned in your first screenshot, to get some more informations.

**Comment by pfefferle** [comment]
@zunaid321 @chaion07 does the email address maybe bounce emails from WP.org?

**Comment by zunaid321** [comment]
No it doesn't any emails from WP.org.

We did receive this email from `wordpress@make.wordpress.org`

`Hi,

You've been invited to join 'Make WordPress Hosting' at
https://make.wordpress.org/hosting with the role of Test Reporter.

Please click the following link to confirm the invite:
https://make.wordpress.org/hosting/newbloguser/xxxx/`

**Comment by zunaid321** [comment]
The account has been unbanned, thanks to one of the moderators in the forum channel.

Also got the application password. Thank you for all the help guys! Much appreciated!

**Comment by chaion07** [comment]
I think we can close this issue now. Thanks so much @Crixu , @pfefferle and @zunaid321 🙌
