### ISSUE TITLE
PHP error when running php prepare.php immediately after cloning, before creating .env file

### ISSUE THREAD

**Issue by jadonn** [WordPress/phpunit-test-runner#45]
While experimenting with the PHP unit test runner, I found that PHP 5.6 and PHP 7.0 encounter a fatal PHP error when the command `php prepare.php` is run immediately after cloning, before creating a local .env file. PHP recorded the following error in the error log:
[28-Aug-2017 14:46:52 UTC] PHP Warning:  fwrite() expects parameter 1 to be resource, string given in /path/to/public_html/phpunit-test-runner/functions.php on line 64

The actual command returned the following output:
`Content-type: text/html; charset=UTF-8`

Not necessarily a huge issue, but it may be worthwhile to add error catching for this use case since the test suite provides more informative feedback in other problematic situations, such as when needed environment vars are not defined in .env or in the environment.

**Comment by danielbachhuber** [comment]
> Not necessarily a huge issue, but it may be worthwhile to add error catching for this use case since the test suite provides more informative feedback in other problematic situations, such as when needed environment vars are not defined in .env or in the environment.

@jadonn It looks like it's actually trying to display a log message and/or error:

https://github.com/WordPress/phpunit-test-runner/blob/master/functions.php#L55

Do you know why `STDOUT` or `STDERR` might not be defined?

**Comment by jadonn** [comment]
I think I see what might be going on. It looks like it was something wonky with the configuration for the PHP binary that was being used to run the test. I tried a different binary, and the error output came out fine. For some reason my server's main PHP binary was linked to the CGI/web binary for PHP instead of the CLI binary. Running with the CGI/web binary appears to generate these errors. Given that these binaries are slightly different, should preference be given to one binary over the other for running the tests? I understand the unit tests may be configured to be run with PHP's CLI binary, but WordPress is going to be executed with the CGI/web binary.

I'm fine, too, with this issue being closed since it seems like it may not actually be an issue.

**Comment by danielbachhuber** [comment]
> Running with the CGI/web binary appears to generate these errors. Given that these binaries are slightly different, should preference be given to one binary over the other for running the tests?

At this point, the preference is to run the tests with the PHP CLI binary. Running against a web binary is an interesting idea but I suspect many aspects about PHPUnit are liable to break.
