### ISSUE TITLE
PHP Unit Test

### ISSUE THREAD

**Issue by TestingCloudways** [WordPress/phpunit-test-runner#53]
Hi there,

I'm Mustaasam from [Cloudways](https://www.cloudways.com/en/) - A Managed Cloud hosting platform.

I'm conducting the WordPress PHP Unit Test as guided [here](https://make.wordpress.org/hosting/test-results-getting-started/) and followed by [GitHub](https://github.com/WordPress/phpunit-test-runner).

For the purpose, I need to be added as a “Test Reporter” on WordPress.org site. Here is the email for WordPress.org account: mustaasam@hotmail.com

Looking forward to it.

Thanks!

**Comment by danielbachhuber** [comment]
Hi @TestingCloudways!

> For the purpose, I need to be added as a “Test Reporter” on WordPress.org site. Here is the email for WordPress.org account:

This should be a bot account, not a personal account. Are you planning to change the email address after the account is accepted?

**Comment by TestingCloudways** [comment]
Hi @danielbachhuber 
Thanks for your reply. I have another account with the official email of Cloudways (mustaasam.saleem@cludways.com). However, the username is different from what was suggested [here](https://make.wordpress.org/hosting/test-results-getting-started/). So I decided to make another account with a different email address as I'm unable to change the WP.org username to something like CloudwaysBot.

**Comment by danielbachhuber** [comment]
Can you register a brand new WordPress.org user account, with username `cloudwaysbot`?

**Comment by TestingCloudways** [comment]
Sure, let me do it.
Just one thing, is it necessary to use "xyz@cloudways.com" or, I can use any other personal email?

**Comment by danielbachhuber** [comment]
You can start with whatever email you'd like, and later change it when a new one is created.

**Comment by TestingCloudways** [comment]
@danielbachhuber 
Can you suggest a username other than the "CloudwaysBot"? We have a separate project named [CloudwaysBot](https://www.cloudways.com/en/cloudwaysbot.php). This is just on the safe so that it may not collide with our product.

**Comment by danielbachhuber** [comment]
@TestingCloudways CloudwaysTests? CloudwaysWPCompat?

**Comment by TestingCloudways** [comment]
@danielbachhuber 
An account has been created:
Username: cloudwaystests
Email: mcg@cloudways.com

**Comment by danielbachhuber** [comment]
Great, I've sent a second invite to that email address.
