### ISSUE TITLE
Add Human Made test reporter

### ISSUE THREAD

**Issue by nathanielks** [WordPress/phpunit-test-runner#54]
Hiya, team!

Would it be possible to add a test reporter for `humanmadebot`, nathaniel@humanmade.com? That email will get changed in the future, just need it set to mine for now.

**Comment by nathanielks** [comment]
actually, it can be set to hosting@humanmade.com :smile:

**Comment by danielbachhuber** [comment]
I've sent an invite to join the site as 'Test Reporter' to nathaniel@humanmade.com. Once you accept, you can generate an application password. You can also change your email address associated with the `humanmadebot` account.
