### ISSUE TITLE
add "makemybot" as test reporter

### ISSUE THREAD

**Issue by vsamukov** [WordPress/phpunit-test-runner#63]
subj please

**Comment by danielbachhuber** [comment]
👋 Can you share the email address associated with this user, and the company it represents?

**Comment by vsamukov** [comment]
V.samukov@gmail.com
Represents an individual enthusiast, but actually Plesk. I'm doing this to
improve on boarding process and perhaps make the documentation a bit
clearer (in a copy-paste to console way) for our partners who are willing
to participate

пт, 15 июн. 2018 г., 18:31 Daniel Bachhuber <notifications@github.com>:

**Comment by danielbachhuber** [comment]
Ok. Do you plan to submit test reports on a regular basis from this user? If so, can you register an official account (e.g. `pleskbot` or similar)?

**Comment by vsamukov** [comment]
Don't think so. This is just to experience the process from beginning to
the end to be able to help others. If you'd like to make my reports
invisible for public this is fine too.
I'll speak to our CTO if official bot needs to be there.

пт, 15 июн. 2018 г., 18:39 Daniel Bachhuber <notifications@github.com>:

**Comment by danielbachhuber** [comment]
Ok. I've gone ahead and invited your account to the site as a `Test Reporter`.

Please let me know when you're done with your documentation steps and I'll remove the account from the site (which will prevent it from showing up as a delinquent reporter).

**Comment by vsamukov** [comment]
done. successfully reported some error (
https://make.wordpress.org/hosting/test-results/r43347/makemybot-r43347/)
not sure if it is of my hosting engine or grunt utility itself:)
documentation is also done, i'll communicate it via our CTO.
please go ahead and kill the bot if you'd like to.
thanks for assistance!

**Comment by danielbachhuber** [comment]
Thanks! I've removed your account from the site.
