### ISSUE TITLE
Add seravobot as "Test reporter"

### ISSUE THREAD

**Issue by ottok** [WordPress/phpunit-test-runner#68]
Please add a new test reporter

Username | Email
-- | --
seravobot | hostmaster@seravo.com

Thanks!

**Comment by danielbachhuber** [comment]
👋 I get an error that the user doesn't exist:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/36432/41465766-5cbc2e8c-7054-11e8-92a4-004adb9aca03.png">

Can you make sure the user is registered on WordPress.org with that email address?

**Comment by ottok** [comment]
Sorry, there was a typo in the domain, correct is seravo.com.

**Comment by danielbachhuber** [comment]
Thanks! Invite sent; you're now free to continue with the setup process.
