### ISSUE TITLE
Please Add my Test Reporter

### ISSUE THREAD

**Issue by HimanshuJoshi18** [WordPress/phpunit-test-runner#69]
I performed the test and the result is here,  Please let me know if its good to go 

---------------------------------------------------
 
You should really fix these slow tests (>150ms)...
 1. 2823ms to run Tests_Media:test_multiline_comment_with_embeds
 2. 1855ms to run Tests_WP_Site_Icon:test_insert_cropped_attachment
 3. 1706ms to run WP_Test_REST_Users_Controller:test_get_items_pagination_headers
 4. 1576ms to run Tests_Image_Functions:test_wp_crop_image_url
 5. 1504ms to run Tests_Media:test_autoembed_no_paragraphs_around_urls
 6. 1252ms to run Tests_Media:test_oembed_explicit_media_link
 7. 1139ms to run WP_Test_REST_Posts_Controller:test_get_items_pagination_headers
 8. 1082ms to run Tests_Image_Functions:test_inferred_mime_types
 9. 968ms to run Tests_WP_Site_Icon:test_create_attachment_object
 10. 950ms to run Tests_Import_Import:test_double_import
...and there are 194 more above your threshold hidden from view

Time: 5.57 minutes, Memory: 403.25MB

OK, but incomplete, skipped, or risky tests!
Tests: 8702, Assertions: 36182, Skipped: 6, Risky: 8.
--------------------------------

**Comment by danielbachhuber** [comment]
Looks good! Have you [followed the other setup steps](https://make.wordpress.org/hosting/test-results-getting-started/), including registering a WordPress.org account for your bot?

**Comment by HimanshuJoshi18** [comment]
I registered WordPress.org account, but unable to proceed further.

**Comment by HimanshuJoshi18** [comment]
Do you require email id/Username associated with the account ?

**Comment by danielbachhuber** [comment]
Yes, I'll need the email address for the account in order to invite the account to the site.

**Comment by HimanshuJoshi18** [comment]
its himanshu@znetlive.com

**Comment by danielbachhuber** [comment]
Ok. What is the WordPress.org username?

**Comment by HimanshuJoshi18** [comment]
znetlivebot

**Comment by danielbachhuber** [comment]
Great! I've sent an invite to the account and you can proceed with the remaining setup steps.

**Comment by rccess** [comment]
we are using wordpress on our few sites (will all Premium themes & Plugins ) but facing speed issues sometimes
[https://mailcot.com](https://mailcot.com)
[https://vmayo.com](https://vmayo.com)
[https://fleely.com](https://fleely.com)
