### ISSUE TITLE
Error: Error uploading results: Invalid parameter(s): commit, message (HTTP status 400)

### ISSUE THREAD

**Issue by HimanshuJoshi18** [WordPress/phpunit-test-runner#70]
I performed the final reporting

and run following command gives me error in uploading result. 

php report.php

---------------------------------------------------
 
Environment variables pass checks.
Getting SVN Revision
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
Getting SVN message
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
Copying junit.xml results
rsync -rv '/tmp/wp-test-runner'/tests/phpunit/build/logs/* '/tmp/wp-test-runner'
sending incremental file list
env.json
junit.xml

sent 1,626,388 bytes  received 54 bytes  3,252,884.00 bytes/sec
total size is 1,625,842  speedup is 1.00
Processing and uploading junit.xml
Error: Error uploading results: Invalid parameter(s): commit, message (HTTP status 400)

--------------------------------

**Comment by danielbachhuber** [comment]
Hi @HimanshuJoshi18,

This seems to be the issue addressed with #61. Let me verify that pull request works as expected.

**Comment by danielbachhuber** [comment]
This is fixed by #61
