### ISSUE TITLE
SAKURA_WebHosting Test Reporter

### ISSUE THREAD

**Issue by holly** [WordPress/phpunit-test-runner#71]
Hey!

We'd like to complete our test reporter setup. The info we've registered for this at WP.org is the following:

Username | Email
-- | --
hollyroyaltea | emperor.kurt __at__ gmail.com

**Comment by danielbachhuber** [comment]
Hi @holly,

Could you register an account like `sakurabot` with an official organization email address? This will make it more obvious who the test results are for.

Thanks!

**Comment by holly** [comment]
Hi @danielbachhuber 

This is the official account.

Username | Email
-- | --
sakurabot | is-ml@sakura.ad.jp

**Comment by danielbachhuber** [comment]
Thanks! I've sent an invite to your user account. Once you accept, you'll be able to complete the signup steps.
