### ISSUE TITLE
Test Result Submitted - Detect the Wrong PHP Version

### ISSUE THREAD

**Issue by wpwebhost** [WordPress/phpunit-test-runner#73]
The test result submitted looks to be detecting the wrong PHP version.

When we build the prepare.php, test.php and report.php, we specifically use the PHP 7.1 to run the script. 

This is the test result https://make.wordpress.org/hosting/test-results/r43377/wpwebhostbot-r43377/

How do we get the test result to show the right version of PHP?

thanks,

**Comment by danielbachhuber** [comment]
Related #56

To confirm, you've set the `WPT_PHP_EXECUTABLE` environment variable?

**Comment by wpwebhost** [comment]
Yep, it's defined. 

As the test requires at least PHP 5.6 to go through. If it's not defined, it won't go through. Here's a sample which it is using the default $PATH that was on the root .bash_profile that it detects the system default install of PHP 5.4.16, upon commenting that, we are able to define to use PHP 7.1 to complete the test and generate the report. But somehow the test result submitted is showing 5.4.16.

[root@wpe1 phpunittest]# /opt/plesk/php/7.1/bin/php test.php 
Environment variables pass checks.
cd '/var/www/vhosts/wphosttest.blog/httpdocs/phptest'; php phpunit.phar
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

This version of PHPUnit is supported on PHP 5.6, PHP 7.0, and PHP 7.1.
You are using PHP 5.4.16 (/usr/bin/php).
Error: Failed to perform operation.

**Comment by wpwebhost** [comment]
Further scrolling through back the history in the terminal, I noticed even when we issue it as PHP 7.1, when the test is being carried out, it's detecting as PHP 5.4.16. I will clear the folder and rerun and resubmit and see if it works correctly.

[root@wpe1 phpunittest]# /opt/plesk/php/7.1/bin/php test.php 
Environment variables pass checks.
cd '/var/www/vhosts/wphosttest.blog/httpdocs/phptest'; /opt/plesk/php/7.1/bin/php phpunit.phar

**PHP version: 5.4.16 (/usr/bin/php)**

Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

**Comment by wpwebhost** [comment]
I have resubmit the test and it looks to be detecting the right version !.
