### ISSUE TITLE
XSERVER WebHosting Test Reporter

### ISSUE THREAD

**Issue by J-KEI** [WordPress/phpunit-test-runner#75]
Hey!

We'd like to complete our test reporter setup. The info we've registered for this at WP.org is the following:

|  Username   |             Email              |
| ----------- | ------------------------------ |
| xserverbot  | `wp_xserverbot@xserver.co.jp`  |
| xserver2bot | `wp_xserverbot2@xserver.co.jp` |

**Comment by danielbachhuber** [comment]
Thanks @J-KEI! I've sent invites to the two usernames mentioned. You'll need to confirm access for each, and then complete the setup process accordingly.
