### ISSUE TITLE
Test Reporter | MyyWP Wordpress Hosting | username : myywp

### ISSUE THREAD

**Issue by RedS-TheUnbeaten** [WordPress/phpunit-test-runner#80]
WP.org Username | WP.org E-Mail
-------------------- | ----------------
myywp | gappsgames2017@gmail.com

**Comment by danielbachhuber** [comment]
Sorry, which web host is this for?

**Comment by earnjam** [comment]
Closing due to lack of response. Happy to reopen if we ever hear back.
