### ISSUE TITLE
Failures details in default testsuite not reported due to core unit test changes

### ISSUE THREAD

**Issue by earnjam** [WordPress/phpunit-test-runner#83]
I noticed yesterday that errors/failures were not showing the specific failures in the single-result view properly. Example:
https://make.wordpress.org/hosting/test-results/r44742/wpdevbot-r44742/

In https://core.trac.wordpress.org/changeset/43768 we added unit tests for the new autosave REST API endpoint. Because of the `DOING_AUTOSAVE` polluting tests, they had to be separated out and run last. This essentially leads to two root level testsuites, which `process_junit_xml()` isn't accounting for. 

![image](https://user-images.githubusercontent.com/4267290/52782469-22f24b80-301d-11e9-8983-89293b8444ee.png)

There is a core ticket for addressing the unit tests specifically, but wondering if we should better handle it here to be less brittle too. https://core.trac.wordpress.org/ticket/45132

**Comment by getsource** [comment]
As reference for anyone checking into this, here is a good place to start:
https://github.com/WordPress/phpunit-test-runner/blob/master/functions.php#L106

**Comment by pfefferle** [comment]
Can someone provide a test result file with errors?

**Comment by getsource** [comment]
Sure, here's one in a gist:
https://gist.github.com/getsource/4053c52ef3b4e83137891721fce4178e

And, a [direct link to the raw file](https://gist.githubusercontent.com/getsource/4053c52ef3b4e83137891721fce4178e/raw/5bb37185fb37f5e7d481c3a18cff9066e90400c5/junit.xml), since gist doesn't seem to like how big the file is.

**Comment by pfefferle** [comment]
Thanks!

Should the refactoring be generic, to handle all levels of nested tests, or should we work on a pragmatic change, that only handles the new test structure of the WordPress core?

**Comment by getsource** [comment]
My initial thoughts: If I understand the issue properly, ideally it would handle cases where additional groups of tests are added, but wouldn't necessarily need to handle infinite nesting.

Depending on the end complexity, though, I can definitely see multiple solutions being fine here, so would be interested to see whatever you think is best!

**Comment by earnjam** [comment]
Ideally core would be adjusted to not separate out these tests and we’d go back to just one test suite. But that’s probably a more challenging task. 

I don’t think we necessarily need to handle infinite nesting. I don’t foresee core adding any deeper nesting than we currently have. But that may not be a safe assumption as seen by the existence of this problem 🙂

**Comment by pfefferle** [comment]
I submitted a first try. The result of the XML file @getsource provided is:

```JSON
{
  "tests": "10279",
  "failures": "3",
  "errors": "1",
  "time": "169.605525",
  "testsuites": {
    "Tests_Image_Functions": {
      "name": "Tests_Image_Functions",
      "tests": "17",
      "failures": "3",
      "errors": "1",
      "testcases": {
        "test_wp_generate_attachment_metadata_pdf": {
          "name": "test_wp_generate_attachment_metadata_pdf",
          "failure": "Tests_Image_Functions::test_wp_generate_attachment_metadata_pdf\nFailed asserting that Array &0 () is identical to Array &0 (\n    'sizes' => Array &1 (\n        'full' => Array &2 (\n            'file' => 'wordpress-gsoc-flyer-pdf.jpg'\n            'width' => 1088\n            'height' => 1408\n            'mime-type' => 'image\\/jpeg'\n        )\n        'medium' => Array &3 (\n            'file' => 'wordpress-gsoc-flyer-pdf-232x300.jpg'\n            'width' => 232\n            'height' => 300\n            'mime-type' => 'image\\/jpeg'\n        )\n        'large' => Array &4 (\n            'file' => 'wordpress-gsoc-flyer-pdf-791x1024.jpg'\n            'width' => 791\n            'height' => 1024\n            'mime-type' => 'image\\/jpeg'\n        )\n        'thumbnail' => Array &5 (\n            'file' => 'wordpress-gsoc-flyer-pdf-116x150.jpg'\n            'width' => 116\n            'height' => 150\n            'mime-type' => 'image\\/jpeg'\n        )\n    )\n).\n\n\\/tmp\\/wp-current-test\\/tests\\/phpunit\\/tests\\/image\\/functions.php:466\n"
        },
        "test_crop_setting_for_pdf": {
          "name": "test_crop_setting_for_pdf",
          "failure": "Tests_Image_Functions::test_crop_setting_for_pdf\nFailed asserting that Array &0 () is identical to Array &0 (\n    'sizes' => Array &1 (\n        'full' => Array &2 (\n            'file' => 'wordpress-gsoc-flyer-pdf.jpg'\n            'width' => 1088\n            'height' => 1408\n            'mime-type' => 'image\\/jpeg'\n        )\n        'medium' => Array &3 (\n            'file' => 'wordpress-gsoc-flyer-pdf-300x300.jpg'\n            'width' => 300\n            'height' => 300\n            'mime-type' => 'image\\/jpeg'\n        )\n        'large' => Array &4 (\n            'file' => 'wordpress-gsoc-flyer-pdf-791x1024.jpg'\n            'width' => 791\n            'height' => 1024\n            'mime-type' => 'image\\/jpeg'\n        )\n        'thumbnail' => Array &5 (\n            'file' => 'wordpress-gsoc-flyer-pdf-116x150.jpg'\n            'width' => 116\n            'height' => 150\n            'mime-type' => 'image\\/jpeg'\n        )\n    )\n).\n\n\\/tmp\\/wp-current-test\\/tests\\/phpunit\\/tests\\/image\\/functions.php:531\n"
        },
        "test_fallback_intermediate_image_sizes": {
          "name": "test_fallback_intermediate_image_sizes",
          "failure": "Tests_Image_Functions::test_fallback_intermediate_image_sizes\nThe `test-size` was not added to the metadata.\nFailed asserting that false is true.\n\n\\/tmp\\/wp-current-test\\/tests\\/phpunit\\/tests\\/image\\/functions.php:572\n"
        },
        "test_pdf_preview_doesnt_overwrite_existing_jpeg": {
          "name": "test_pdf_preview_doesnt_overwrite_existing_jpeg",
          "error": "Tests_Image_Functions::test_pdf_preview_doesnt_overwrite_existing_jpeg\nUndefined index: sizes\n\n\\/tmp\\/wp-current-test\\/tests\\/phpunit\\/tests\\/image\\/functions.php:620\n"
        }
      }
    }
  }
}
```

**Comment by getsource** [comment]
On my test environment, this looks function as expected, and results+ errors upload properly.

**Comment by pfefferle** [comment]
Does the frontend strip the result to 4 items? I had 26 errors in the test, but the frontend only shows 4: https://make.wordpress.org/hosting/test-results/r47535/ionosbot-r47535/

**Comment by pfefferle** [comment]
Found the problem... It was the same test, with multiple asserts...

**Comment by pfefferle** [comment]
It shows the last 4 tests

**Comment by pfefferle** [comment]
Ah, it seems to show only the latest test-suite...

**Comment by getsource** [comment]
I haven't dug into this beyond finding it, but here is the relevant code on the reporter side -- looks like it might be related to the issue?
https://github.com/WordPress/phpunit-test-reporter/blob/master/parts/single-result.php#L75

**Comment by getsource** [comment]
Thanks so much @pfefferle !
