### ISSUE TITLE
Please add wpcloudbot as test reporter

### ISSUE THREAD

**Issue by joonasvanhatapio** [WordPress/phpunit-test-runner#88]
![image](https://user-images.githubusercontent.com/6750808/53956313-f396a200-40e3-11e9-87d7-7af5ea9f17d4.png)

**Comment by earnjam** [comment]
@joonasvanhatapio Can you make sure the avatar and display name on the account clearly indicate which hosting company this account belongs to?

**Comment by ottok** [comment]
Can you please use another email for this account, and ensure that email has as the gravatar your company logo? The username is OK.

**Comment by joonasvanhatapio** [comment]
Sorry for delay. We have now created a new email address for this purpose and setup it's avatar to match our company logo.

![image](https://user-images.githubusercontent.com/6750808/54538792-93ceaf80-499d-11e9-9ed7-6e89b72a3e1f.png)

**Comment by getsource** [comment]
Hey @joonasvanhatapio! Sorry for the wait.

I tried to add that one, but it looks like it doesn't currently have a WordPress.org account associated with it.

If you think something is wrong, and it does, please list its WordPress.org account here, too, and I'll try that instead.

Thanks much!

**Comment by joonasvanhatapio** [comment]
Hi Mike,

It should work right now with that email, I had forgotten to verify the new email for that user.

Thanks!

**Comment by getsource** [comment]
Done; thank you! Please let me know if you run into any trouble or have any questions.
