### ISSUE TITLE
Please add user as Test Reporter

### ISSUE THREAD

**Issue by Tuomas-dev** [WordPress/phpunit-test-runner#94]
Hi,

Please add a new user as a Test Reporter.
Bot username: tuonettibot
Email: admin@tuonetti.fi

Thank you in advance.

**Comment by getsource** [comment]
Added; thanks much!

You should get a confirmation email soon, after which you should be able to generate/view your API key from within your profile in the https://make.wordpress.org/hosting/wp-admin panel.

Please let me know if you run into any trouble!
