### ISSUE TITLE
New test reporter

### ISSUE THREAD

**Issue by todeveni** [WordPress/phpunit-test-runner#95]
New reporter reporting for duty.

Bot username: managedbot
Email: some@managed.fi

**Comment by earnjam** [comment]
@todeveni Can you update the display name/nicename on that wp.org profile so that it's clear for users visiting the test results page who the hosting company is? Right now it would just show as `managedbot`. 

Thanks!

**Comment by todeveni** [comment]
@earnjam Done, thanks.

**Comment by todeveni** [comment]
Ping @earnjam

**Comment by getsource** [comment]
Apologies for the wait @todeveni! Added, and you should receive an invite to the WP.org user's registered email account.
