### ISSUE TITLE
Test Reporter access request.

### ISSUE THREAD

**Issue by mrxkon** [WordPress/phpunit-test-runner#96]
Hey!

I've created the bot account as needed and already have an environment running the tests and everything looks good ( I have to also say that the setup was super smooth! ). So we're just missing the acces now 😄  ! Could you please add us as Test Reporters as well?

**wp.org username:** wpmudevbot
**e-mail:** contact+wpmudevbot@wpmudev.org
**url:** https://premium.wpmudev.org/
**host:** WPMU DEV

Thanks in advance!

**Comment by earnjam** [comment]
Invite sent! Let me know if you have any questions/issues with the rest
