### ISSUE TITLE
Test Reporter addition

### ISSUE THREAD

**Issue by MazeWebArchitect** [WordPress/phpunit-test-runner#97]
Hey there,
we would like to participate in the PHP Unit Tests.

Handle: @raidboxes on WordPress.org
E-Mail: wp-dev@raidboxes.de

Also

Handle: @mazeheld on WordPress.org
E-Mail: mazeme@gmail.com

Thank you very much

**Comment by earnjam** [comment]
Invite sent for `@raidboxes`. Waiting on a new handle for the 2nd one per our discussion in Slack.
